MAIN - updates buttons
VivyTeam/vivy-components pull request #351
Opened 2019-04-18 11:07 UTC by paschalidi

🥁 🥁 🥁 🥁  Happy to present to you  🥁 🥁 🥁 🥁 
our 
✨ **n e w**  ✨ **a m a z i n g** ✨ **b u t t o n s** ✨

#### On the details!
* `height` designers told me that would be 3 heights 56 40 and 32. Property `height` now can take three values `lg`,`sm`, `basic`(basic is the default value)
* restricted the already existing property `type` to: `type: PropTypes.oneOf(["primary", "secondary"])`
* instead of hardcoded hex colors this time we use our own `Colors`!
* wrote cool stories about all the different cases

#### g i f s  ftw!
![anchor-buttons](https://user-images.githubusercontent.com/4181674/56357073-e2f54380-61da-11e9-835d-e615c7778898.gif)
![buttons](https://user-images.githubusercontent.com/4181674/56357075-e38dda00-61da-11e9-8472-de5910ecf9e3.gif)

2019-04-18 11:23 UTC, paschalidi commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  
  DangerID: danger-id-default;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>✅  Get a 🏆 for adding description on this PR. - <i>Celebrate on every step!</i></td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>✅ Get a 👍 for requesting reviewers. - <i>Celebrating every win!</i></td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7687932fa3f8441905a74d5ef7204b54b3908362
</p>

2019-04-23 08:19 UTC, Weetbix requested changes
Looks good, 

I would say better to name the stories after the attribute names rather than the implemented value, I made some suggestions

2019-04-23 08:19 UTC, Weetbix commented on stories/AnchorButton.story.jsx
> +  .add("primary height 56", () => (
```suggestion
  .add("primary height large", () => (
```

2019-04-23 08:19 UTC, Weetbix commented on stories/AnchorButton.story.jsx
> +  .add("primary height 32", () => (
```suggestion
  .add("primary height small", () => (
```

2019-04-23 08:19 UTC, Weetbix commented on stories/AnchorButton.story.jsx
> +  .add("secondary height 56", () => (
```suggestion
 .add("secondary height large", () => (
```

2019-04-23 08:19 UTC, Weetbix commented on stories/AnchorButton.story.jsx
> +  .add("secondary height 32", () => (
```suggestion
  .add("secondary height small", () => (
```

2019-04-23 08:19 UTC, Weetbix commented on stories/Button.story.jsx
> +  .add("primary height 56", () => <Button height="lg">Call to Action</Button>)
```suggestion
  .add("primary height large", () => <Button height="lg">Call to Action</Button>)
```

2019-04-23 08:19 UTC, Weetbix commented on stories/Button.story.jsx
> +  .add("primary height 32", () => <Button height="sm">Call to Action</Button>)
```suggestion
  .add("primary height small", () => <Button height="sm">Call to Action</Button>)
```

2019-04-23 08:19 UTC, Weetbix commented on stories/Button.story.jsx
> +  .add("secondary height 56", () => (
```suggestion
  .add("secondary height large", () => (
```

2019-04-23 08:19 UTC, Weetbix commented on stories/Button.story.jsx
> +  .add("secondary height 32", () => (
```suggestion
  .add("secondary height small", () => (
```

2019-04-23 08:26 UTC, paschalidi commented
> I would say better to name the stories after the attribute names rather than the implemented value, I made some suggestions

Absolutely agree. At the beginning I implemented this such as we parse a number in the component but then decided to change it to string, therefore I forgot to change the story names.. 
Good catch! 

Thanks for the review!

2019-04-23 12:21 UTC, Weetbix approved these changes

2019-04-23 12:22 UTC, merged