MAIN - adds a property on modal that will disable/enable submit button on modal
VivyTeam/vivy-components pull request #363
Opened 2019-04-25 08:21 UTC by paschalidi

hello you 👋 👋 @VivyTeam/web 

There are some use cases have submission disabled in our `Modal` components.

This PR will add a property `submissionEnabled ` on the Modal that will make this possible.

2019-04-25 08:26 UTC, paschalidi commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>✅  Get a 🏆 for adding description on this PR. - <i>Celebrate on every step!</i></td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>✅ Get a 👍 for requesting reviewers. - <i>Celebrating every win!</i></td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eae88e028058e594d1cbce84aec6c9363b31c11c
</p>

2019-04-26 12:37 UTC, Weetbix requested changes
Cool 😎 Few minor comments

2019-04-26 12:37 UTC, Weetbix commented on src/Modal/Modal.jsx
> +  submissionEnabled: false,
think a more sensible default might be true, seems like the most common use case (info prompts etc)

2019-04-26 12:37 UTC, Weetbix commented on stories/Modal.story.jsx
> +      const [actionComplete, toggleSubmissionState] = useState(false);
`actionComplete` might be better named `allowSubmit`?

2019-04-29 09:05 UTC, paschalidi commented
@Weetbix the changes you requested are there by now! Thanks for reviewing!

2019-04-30 09:44 UTC, Weetbix approved these changes
Thank you sir!

2019-04-30 09:44 UTC, merged